FacturacionWeb/Controllers/ClienteController.cs
using CapaLogica;
using EntidadesCompartidas;
using FacturacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacturacionWeb.Controllers
{
    public class ClienteController : Controller
    {
        LogicaCliente logCli = new LogicaCliente();

        // GET: Cliente
        public ActionResult ListaCliente()
        {
            var lista = logCli.ListarClientes();
            List<ClienteModel> listaModel = new List<ClienteModel>();

            foreach (ClienteDTO c in lista)
            {
                ClienteModel cli = new ClienteModel();
                cli.ClienteID = c.ClienteID;
                cli.NombreCliente = c.NombreCliente;
                cli.FechaNacimiento = c.FechaNacimiento;
                cli.Domicilio = c.Domicilio;
                cli.Celular = c.Celular;

                listaModel.Add(cli);

            }
            return View(listaModel);
        }




        public ActionResult CrearCliente()
        {
            return View();
        }


        public ActionResult GuardarCliente(ClienteModel model)
        {

            ClienteDTO cli = new ClienteDTO();

            cli.NombreCliente = model.NombreCliente;
            cli.ClienteID = model.ClienteID;
            cli.FechaNacimiento = model.FechaNacimiento;
            cli.Domicilio = model.Domicilio;
            cli.Celular = model.Celular;

            logCli.CrearCliente(cli);

            return RedirectToAction("ListaCliente");

        }



        public ActionResult DetalleCliente(int id)
        {
            var clienteDTOLista = logCli.ListarClientes();
            var clienteDetalle = clienteDTOLista.Where(c => c.ClienteID == id).FirstOrDefault();

            ClienteModel modelo = new ClienteModel()
            {
                ClienteID = clienteDetalle.ClienteID,
                NombreCliente = clienteDetalle.NombreCliente,
                FechaNacimiento = clienteDetalle.FechaNacimiento,
                Domicilio = clienteDetalle.Domicilio,
                Celular = clienteDetalle.Celular,

            };
            return View(modelo);
        }





    }
}

FacturacionWeb/Controllers/FacturaController.cs
using CapaLogica;
using EntidadesCompartidas;
using FacturacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacturacionWeb.Controllers
{
    public class FacturaController : Controller
    {
        //GET: Factura
        private LogicaProducto logicaProducto = new LogicaProducto();
        private LogicaFactura logicaFactura = new LogicaFactura();

        public ActionResult CrearFactura()
        {
            FacturaModel modelSession = new FacturaModel();
            Session.Add("modeloFactura", modelSession);

            ProductoModel prod = new ProductoModel();

            DetalleFacturaModel detalle = new DetalleFacturaModel();

            FacturaModel fac = new FacturaModel();

            fac.detalleFactura.Add(detalle);

            return View();
        }

        [HttpPost]

        public ActionResult CrearFactura(FacturaModel facturaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    return View(facturaModel);
                }
                ProductoDTO detalleFactura = null;

                DetalleFacturaModel detalleModel = new DetalleFacturaModel();

                ProductoDTO detalleProducto = logicaProducto.BuscarProducto(facturaModel.ProductoID);
                if (detalleFactura != null)
                {
                    ProductoModel productoModel = new ProductoModel()
                    {
                        ProductoID = detalleFactura.ProductoID,
                        NombreProducto = detalleFactura.NombreProducto,
                        PrecioUnidad = facturaModel.MontoTotal,
                    };

                    FacturaModel sessionFacturaModel = new FacturaModel();
                    if (Session["modeloFactura"] != null)
                    {
                        sessionFacturaModel = (FacturaModel)Session["modeloFactura"];
                        sessionFacturaModel.detalleFactura.Add(detalleModel);
                        sessionFacturaModel.ClienteID = facturaModel.ClienteID;
                        sessionFacturaModel.FacturaID = facturaModel.FacturaID;

                        sessionFacturaModel.MontoTotal = CalcularTotal(sessionFacturaModel.detalleFactura);
                        Session["modeloFactura"] = sessionFacturaModel;

                        //return View(sessionFacturaModel);
                    }

                    //sessionFacturaModel.detalleFactura.Add(detalleModel);
                    //sessionFacturaModel.ClienteID = facturaModel.ClienteID;
                    //sessionFacturaModel.FacturaID = facturaModel.FacturaID;

                    //sessionFacturaModel.MontoTotal = CalcularTotal(sessionFacturaModel.detalleFactura);
                    //Session["modeloFactura"] = sessionFacturaModel;

                    return View(sessionFacturaModel);
                }
                else
                {
                    ModelState.AddModelError("ProductoID", $"El producto { facturaModel.ProductoID} no existe");
                    return View(facturaModel);
                }
            }

            catch (Exception)
            {
                ViewBag.mensajeError("Ocurrio un error en el servidor");
                return View("~/Views/Shared/Error.cshtml");
            }

        }
        public decimal CalcularTotal(List<DetalleFacturaModel> detalleFactura)
        {
            decimal precioTotal = 0;
            foreach (DetalleFacturaModel item in detalleFactura)
            {

                item.SubTotal = item.Cantidad * item.Prod.PrecioUnidad;
                precioTotal = item.SubTotal;
            }

            return precioTotal;

        }

        [HttpPost]

        public ActionResult GuardarFactura(FacturaModel facturaModel)
        {
            List<DetalleFacturaDTO> listaProductosDTO = new List<DetalleFacturaDTO>();

            LogicaFactura logFac = new LogicaFactura();
            foreach (var item in facturaModel.detalleFactura)
            {
                DetalleFacturaDTO productoDTO = new DetalleFacturaDTO()
                {
                    ProductoID = item.ProductoID,
                    Subtotal = item.SubTotal,
                    FacturaID = facturaModel.FacturaID,
                };

                listaProductosDTO.Add(productoDTO);
            }

            FacturaDTO factura = new FacturaDTO()
            {
                ClienteID = facturaModel.ClienteID,
                FacturaID = facturaModel.FacturaID,
                CostoTotal = facturaModel.CostoTotal,

                ListaProducto = listaProductosDTO
            };

            ProductoModel prod = new ProductoModel();

            DetalleFacturaModel detalle = new DetalleFacturaModel();

            FacturaModel fac = new FacturaModel();

            fac.detalleFactura.Add(detalle);



            logFac.GuardarFactura(factura);
            return RedirectToAction("Guardar", "_ListaDetalle");
        }





    }
}

FacturacionWeb/Controllers/ProductoController.cs
using CapaLogica;
using EntidadesCompartidas;
using FacturacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacturacionWeb.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        LogicaProducto logProdu = new LogicaProducto();


        public ActionResult ListaProducto()
        {
            var lista = logProdu.ListaProducto();
            List<ProductoModel> listaModel = new List<ProductoModel>();

            foreach (ProductoDTO p in lista)
            {
                ProductoModel produ = new ProductoModel();
                produ.ProductoID = p.ProductoID;
                produ.NombreProducto = p.NombreProducto;
                produ.Marca = p.Marca;
                produ.PrecioUnidad = p.PrecioUnidad;
                produ.Descripcion = p.Descripcion;

                listaModel.Add(produ);

            }
            return View(listaModel);
        }



        public ActionResult CrearProducto()
        {
            return View();
        }


        public ActionResult GuardarProducto(ProductoModel model)
        {

            ProductoDTO produ = new ProductoDTO();
            produ.ProductoID = model.ProductoID;
            produ.NombreProducto = model.NombreProducto;
            produ.Marca = model.Marca;
            produ.PrecioUnidad = model.PrecioUnidad;
            produ.Descripcion = model.Descripcion;

            logProdu.CrearProducto(produ);


            return RedirectToAction("ListaProducto");

        }





        public ActionResult DetalleProducto(int id)
        {
            var productoDTOLista = logProdu.ListaProducto();
            var productoDetalle = productoDTOLista.Where(p => p.ProductoID == id).FirstOrDefault();

            ProductoModel modelo = new ProductoModel()
            {
                ProductoID = productoDetalle.ProductoID,
                NombreProducto = productoDetalle.NombreProducto,
                Marca = productoDetalle.Marca,
                PrecioUnidad = productoDetalle.PrecioUnidad,
                Descripcion = productoDetalle.Descripcion,
            };

            return View(modelo);
        }





    }
}

FacturacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Sistema de facturación web", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        @if (Session["Usuario"] != null)
        {
            <ul class="nav navbar-nav">

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Gestión de usuarios
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Crear Usuario", "CrearUsuario", "Usuario")</li>
                        <li>@Html.ActionLink("Lista de Usuarios", "ListarUsuario", "Usuario")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Clientes
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Lista de clientes", "ListaCliente", "Cliente")</li>
                        <li>@Html.ActionLink("Registrar nuevo cliente", "CrearCliente", "Cliente")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Productos
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Lista de productos", "ListaProducto", "Producto")</li>
                        <li>@Html.ActionLink("Registrar nuevo producto", "CrearProducto", "Producto")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Facturas
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Registrar nueva factura", "CrearFactura", "Factura")</li>
                    </ul>
                </li>
            </ul>


        }


                @*<div class="container">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="https://image.freepik.com/vector-gratis/conjunto-de-empresario-y-los-iconos-aislados-en-fondo-blanco_7562-9.jpg" alt="Gestionar usuarios" style="width:70%;">
                            </div>
                        


                            <div class="item">
                                <img src="http://fevas.org/wp-content/uploads/2017/02/accesibilidad.jpg" alt="Clientes" style="width:70%;">
                            </div>
                           
                        

                            <div class="item">
                                <img src="https://thumbs.dreamstime.com/t/icono-del-carro-de-la-compra-en-la-tableta-digital-por-los-productos-del-arte-91392558.jpg" alt="Nuestros productos" style="width:70%;">
                            </div>
                            


                            <div class="item">
                                <img src="http://www.facturador.ame.gob.ec/img/icono-FACTURA-elecronica.jpg" alt="Facturas" style="width:70%;">
                            </div>
                           
                        </div>

                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>*@


                   
</div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>